Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> 2 + 3
5
>>> Me = Lee
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    Me = Lee
NameError: name 'Lee' is not defined
>>> printf("Lee")
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    printf("Lee")
NameError: name 'printf' is not defined
>>> 7+8
15
>>> 7/3
2.3333333333333335
>>> i = 100
>>> i/50
2.0
>>> i*7
700
>>> i
100
>>> i
100
>>> if "사과" in ["딸기", "바나나", "사과"]:
	printf("사과가 있습니다")

	
Traceback (most recent call last):
  File "<pyshell#12>", line 2, in <module>
    printf("사과가 있습니다")
NameError: name 'printf' is not defined
>>> if "사과" in ["딸기", "바나나", "사과"]:
	print("사과가 있습니다")

	
사과가 있습니다
>>> print = 1000
>>> print
1000
>>> if "사과" in ["딸기", "바나나", "사과"]:
	print("사과가 있습니다")

	
Traceback (most recent call last):
  File "<pyshell#18>", line 2, in <module>
    print("사과가 있습니다")
TypeError: 'int' object is not callable
>>> 
=============================== RESTART: Shell ===============================
>>> i
Traceback (most recent call last):
  File "<pyshell#19>", line 1, in <module>
    i
NameError: name 'i' is not defined
>>> i = 100
>>> i
100
>>> print("aa")
aa
>>> print("Python is SO MUCH fun!!!")
Python is SO MUCH fun!!!
>>> 창의적 사고와 코딩
SyntaxError: invalid syntax
>>> 창사코
Traceback (most recent call last):
  File "<pyshell#25>", line 1, in <module>
    창사코
NameError: name '창사코' is not defined
>>> print("창의적 사고와 코딩")
창의적 사고와 코딩
>>> list
<class 'list'>
>>> lee
Traceback (most recent call last):
  File "<pyshell#28>", line 1, in <module>
    lee
NameError: name 'lee' is not defined
>>> lee = 1996
>>> lee/499
4.0
>>> lee
1996
>>> lee - i
1896
>>> -i
-100
>>> lee - 100i
SyntaxError: invalid syntax
>>> lee - 100*i
-8004
>>> hello world
SyntaxError: invalid syntax
>>> print("Hello World")
Hello World
>>> "hello world"
'hello world'
>>> 'hello world'
'hello world'
>>> 'Lee Kang Hoon'
'Lee Kang Hoon'
>>> Print("Lee Kang Hoon")
Traceback (most recent call last):
  File "<pyshell#41>", line 1, in <module>
    Print("Lee Kang Hoon")
NameError: name 'Print' is not defined
>>> print("Lee Kang Hoon")
Lee Kang Hoon
>>> print(lee)
1996
>>> print(i, lee, lee/i)
100 1996 19.96
>>> print(i,lee,'lee/i')
100 1996 lee/i
>>> print('3*4 =', 3*4)
3*4 = 12
>>> print(' 3 * 4 = ', 3*4)
 3 * 4 =  12
>>> print("hello", "world")
hello world
>>> print("hello" = 'world')
SyntaxError: keyword can't be an expression
>>> print('hello' + 'world')
helloworld
>>> print("Hello"+'world')
Helloworld
>>> print("2 * 3 =" + str(2*3))
2 * 3 =6
>>> print("LEE" * 1996)
LEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEELEE
>>> print(lee * 7)
13972
>>> print ('lee' = 1996)
SyntaxError: keyword can't be an expression
>>> print ('kim' = 1999)
SyntaxError: keyword can't be an expression
>>> print("kim" = 1999)
SyntaxError: keyword can't be an expression
>>> lee
1996k
>>> kim
Traceback (most recent call last):
  File "<pyshell#59>", line 1, in <module>
    kim
NameError: name 'kim' is not defined
>>> type(lee)
<class 'int'>
>>> type(kim)
Traceback (most recent call last):
  File "<pyshell#61>", line 1, in <module>
    type(kim)
NameError: name 'kim' is not defined
>>> kim = 1999
>>> kim
1999
>>> park = '1998'
>>> park
'1998'
>>> type(park)
<class 'str'>
>>> print(park * 3)
199819981998
>>> print(str(park)*3)
199819981998
>>> print(int(park)*3)
5994
>>> str(park)
'1998'
>>> int(park)
1998
>>> type(pakr)
Traceback (most recent call last):
  File "<pyshell#72>", line 1, in <module>
    type(pakr)
NameError: name 'pakr' is not defined
>>> type(park)
<class 'str'>
>>> park = int(park)
>>> type(park)
<class 'int'>
>>> park
1998
>>> park = str(park)
>>> park
'1998'
>>> type(park)
<class 'str'>
>>> import turtle
>>> t1 = turtle.Turtle()
>>> t1.shape("turtle")
>>> t2 = turtle.Turtle()
>>> t2.shape("bear")
Traceback (most recent call last):
  File "<pyshell#84>", line 1, in <module>
    t2.shape("bear")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/turtle.py", line 2776, in shape
    raise TurtleGraphicsError("There is no shape named %s" % name)
turtle.TurtleGraphicsError: There is no shape named bear
>>> t2.shape("crab")
Traceback (most recent call last):
  File "<pyshell#85>", line 1, in <module>
    t2.shape("crab")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/turtle.py", line 2776, in shape
    raise TurtleGraphicsError("There is no shape named %s" % name)
turtle.TurtleGraphicsError: There is no shape named crab
>>> t2.shape("dog")
Traceback (most recent call last):
  File "<pyshell#86>", line 1, in <module>
    t2.shape("dog")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/turtle.py", line 2776, in shape
    raise TurtleGraphicsError("There is no shape named %s" % name)
turtle.TurtleGraphicsError: There is no shape named dog
>>> t1.fd(100)
>>> t1.rt(120)
>>> t1.fd(100
	  )
>>> t1.rt(-120)
>>> t1.fd(100)
>>> t1.lt(90)
>>> t1.fd(120)
>>> t1.lt(90)
>>> t1.fd(150)
>>> t1.lt(90)
>>> t1.fd(20)
>>> t2=turtle.Turtle("arrow")
>>> t2.rt(90
	  )
>>> t2.fd(50)
>>> t2.circle(200)
>>> t2.fd(10)
>>> t2.circle(200)
>>> t2.fd(10)
>>> t2.circle(200)
>>> t2.fd(100)
>>> t2.circle(200)
>>> t2.fd(10)
>>> t2.circle(200)
t2.circle
>>> t2.fd(10)
>>> t2.circle(200)
>>> t2.rt(90)
>>> t2.fd(100)
>>> t2.fd(100)
>>> t2.bw(10)
Traceback (most recent call last):
  File "<pyshell#117>", line 1, in <module>
    t2.bw(10)
AttributeError: 'Turtle' object has no attribute 'bw'
>>> t2.backward(10)
>>> t2.circle(100)
>>> t2.fd(10)
>>> t2.circle(100)
t2
>>> t2.fd(10)
>>> t2.circle(100)
>>> t2.rt(90)
>>> t2.fd(150)
>>> t2.circle(150)
>>> t2.fd(10)
>>> t2.circle(150)
>>> t2.fd(10)
>>> t2.circle(150)
>>> 
